version: "3"
   
services:
  db:
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql/data
    
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: progra21
      MYSQL_USER: juan
      MYSQL_PASSWORD: pepito123
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/segura2021
    ports:
      - "8000:8000"
    depends_on:
      - db

