# Generated by Django 2.2.7 on 2021-06-25 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('Nick', models.CharField(max_length=20)),
                ('Correo_electronico', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=1024)),
                ('Llave_publica', models.CharField(max_length=2048, null=True)),
                ('Llave_privada', models.CharField(max_length=2048, null=True)),
                ('Iv', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitio', models.CharField(max_length=20)),
                ('User', models.CharField(max_length=50)),
                ('Iv', models.CharField(max_length=1024)),
                ('Contraseña', models.CharField(max_length=1024)),
                ('detallesExtra', models.CharField(max_length=135)),
                ('nick', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.Usuario')),
            ],
        ),
    ]
